spring:
  application:
    name: umg-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/umg
    username: umg_user
    password: umg_pw
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  error:
    include-stacktrace: NEVER

springdoc:
  api-docs:
    path: /api-docs

spotify:
  clientid: default
  clientsecret: default